### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Unparanormal** [shanetechwiz/node-steamcardbot#11]
C:\Users\Administrator\Desktop\node-steamcardbot-master\node-steamcardbot-master
>node bot.js
C:\Users\Administrator\Desktop\node-steamcardbot-master\node-steamcardbot-master
\config.js:19
                welcome: 'Welcome to Rick's Level up Service, Our current rate i
s 16:1 (Set > Key) Use !help for more informaton to start.',
                                          ^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\node-steamcardbot-mast
er\node-steamcardbot-master\bot.js:25:14)

C:\Users\Administrator\Desktop\node-steamcardbot-master\node-steamcardbot-master
>pause
Press any key to continue . . .

**Comment by shanetechwiz** [comment]
'Welcome to Rick's Level up Service, Our current rate i
s 16:1 (Set > Key) Use !help for more informaton to start.',

You basically closed the string at Rick' 
Anything else after that isn't apart of the string and naturally, you'll get an error.

You could try enclosing the string with double quotes in order to facilitate the apostrophe. Like this:
"Welcome to Rick's Level up Service, Our current rate is 16:1 (Set > Key) Use !help for more information to start."

**Comment by Unparanormal** [comment]
Derp, Got it. Had that multiple times throughout the list. Fixed but now I have a separate spam error. Me and GGrandma were trying to figure out what goes where.


C:\Users\Administrator\Desktop\node-steamcardbot-master\node-steamcardbot-master
>node bot.js
Sun Nov 05 2017 12:51:27 GMT-0800 (Pacific Standard Time) - Connected...
C:\Users\Administrator\Desktop\node-steamcardbot-master\node-steamcardbot-master
\node_modules\long\dist\long.js:310
        return fromBits(val.low, val.high, val.unsigned);
                           ^

TypeError: Cannot read property 'low' of undefined
    at Function.fromValue (C:\Users\Administrator\Desktop\node-steamcardbot-mast
er\node-steamcardbot-master\node_modules\long\dist\long.js:310:28)
    at Function.SteamID.decode (C:\Users\Administrator\Desktop\node-steamcardbot
-master\node-steamcardbot-master\node_modules\steam\lib\steamID.js:19:18)
    at SteamFriends.sendMessage (C:\Users\Administrator\Desktop\node-steamcardbo
t-master\node-steamcardbot-master\node_modules\steam\lib\handlers\friends\index.
js:59:20)
    at log (C:\Users\Administrator\Desktop\node-steamcardbot-master\node-steamca
rdbot-master\bot.js:38:15)
    at SteamClient.<anonymous> (C:\Users\Administrator\Desktop\node-steamcardbot
-master\node-steamcardbot-master\bot.js:50:3)
    at emitNone (events.js:86:13)
    at SteamClient.emit (events.js:185:7)
    at SteamClient.handlers.(anonymous function) (C:\Users\Administrator\Desktop
\node-steamcardbot-master\node-steamcardbot-master\node_modules\steam\lib\steam_
client.js:243:8)
    at SteamClient._netMsgReceived (C:\Users\Administrator\Desktop\node-steamcar
dbot-master\node-steamcardbot-master\node_modules\steam\lib\steam_client.js:157:
26)
    at emitOne (events.js:96:13)

C:\Users\Administrator\Desktop\node-steamcardbot-master\node-steamcardbot-master
>pause
Press any key to continue . . .

**Comment by shanetechwiz** [comment]
Let me see if I can help with this in the other open issue
